name: ImpactU VIP E2E Tests

on:
  push:
    branches: [next_develop]
  workflow_dispatch:

env:
  NEXT_PUBLIC_CLIENT_API: ${{ secrets.NEXT_PUBLIC_CLIENT_API }}
  API_URL: ${{ secrets.API_URL }}
  HOME: /root

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run VIP Playwright tests
        run: npx playwright test tests/vip --output=playwright-report-vip

      - name: Check generated reports
        run: |
          echo "Artifacts folder:"
          ls -la playwright-report-vip || true
          echo "HTML report folder:"
          ls -la playwright-report || true

      - name: Upload HTML report to ci-front-vip
        if: always()
        shell: bash
        run: |
          apt-get update
          apt-get install -y sshpass

          # limpiar carpeta remota
          sshpass -p "${{secrets.SSH_PASS}}" ssh \
          -o UserKnownHostsFile=/dev/null \
          -o StrictHostKeyChecking=no \
          ci-front@ci-front.colav.co \
          "rm -rf /home/ci-front/playwright/playwright-report-vip && mkdir -p /home/ci-front/playwright/playwright-report-vip"

          # copiar HTML report real
          sshpass -p "${{secrets.SSH_PASS}}" scp \
          -o UserKnownHostsFile=/dev/null \
          -o StrictHostKeyChecking=no \
          -r playwright-report/* \
          ci-front@ci-front.colav.co:/home/ci-front/playwright/playwright-report-vip/

          echo "::notice title=HTML report url::https://ci-front.colav.co/playwright-report-vip/index.html"
