name: ImpactU VIP E2E Tests
on:
  push:
    branches: [next_develop]
  workflow_dispatch:
env:
  NEXT_PUBLIC_CLIENT_API: ${{ secrets.NEXT_PUBLIC_CLIENT_API }}
  API_URL: ${{ secrets.API_URL }}
jobs:
  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run VIP Playwright tests
        run: npx playwright test tests/vip
      - name: test folder
        run: ls -la playwright-report-vip
      - name: Upload HTML report to ci-front-vip
        if: always()
        shell: bash
        run: |
          sudo apt install -y sshpass
          sshpass -p "${{secrets.SSH_PASS}}" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r playwright-report-vip/ ci-front@ci-front.colav.co:/home/ci-front/playwright
          echo "::notice title=HTML report url::https://ci-front.colav.co"
