name: ImpactU E2E Tests
on:
  push:
    branches: [next_develop]
  pull_request:
    branches: [main, master]
    types: [opened, closed]
  workflow_dispatch:
env:
  NEXT_PUBLIC_CLIENT_API: ${{ secrets.NEXT_PUBLIC_CLIENT_API }}
  API_URL: ${{ secrets.API_URL }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload HTML report to ci-front
        if: always()
        shell: bash
        run: |
          sudo apt install -y sshpass
          sshpass -p "${{secrets.SSH_PASS}}" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r playwright-report/ ci-front@ci-front.colav.co:
          echo "::notice title=HTML report url::https://ci-front.colav.co/index.html"

  merge:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: echo "Merged PR detected, triggering deployment."

  deploy:
    needs: [test, merge]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker image with ImpactU UI
        shell: bash
        run: |
          sudo apt install -y sshpass
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            export BRANCH_NAME=${{ github.base_ref }}
          else
            export BRANCH_NAME=${GITHUB_REF##*/}
          fi
          echo "Deploying branch $BRANCH_NAME"
          sshpass -p "${{secrets.SSH_PASS}}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ci-front@ci-front.colav.co /home/ci-front/Chia/guatquyca/run-devops.sh $BRANCH_NAME
