name: ImpactU E2E Tests and Deployment

on:
  push:
    branches: [next_develop]
  pull_request:
    branches: [main]
    types: [opened, closed]
  workflow_dispatch:

jobs:
  test:
    name: Run E2E Tests
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    timeout-minutes: 120
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CLIENT_API: ${{ secrets.NEXT_PUBLIC_CLIENT_API }}
      API_URL: ${{ secrets.API_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set production env if on main PR
        if: github.event.pull_request.base.ref == 'main'
        run: |
          echo "NEXT_PUBLIC_CLIENT_API=${{ secrets.NEXT_PUBLIC_CLIENT_API_PROD }}" >> $GITHUB_ENV
          echo "API_URL=${{ secrets.API_URL_PROD }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Playwright tests
        run: npx playwright test tests/e2e --output=playwright-report-e2e

      - name: Upload HTML report to ci-front
        if: always()
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ci-front@ci-front.colav.co "mkdir -p /home/ci-front/playwright/playwright-report-e2e"
          sshpass -p "${{ secrets.SSH_PASS }}" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r playwright-report/* ci-front@ci-front.colav.co:/home/ci-front/playwright/playwright-report-e2e/
          echo "::notice title=HTML report url::https://ci-front.colav.co/playwright-report-e2e/index.html"

  deploy_from_dev:
    name: Deploy from next_develop
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/next_develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker image for dev
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          echo "Deploying next_develop branch"
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ci-front@ci-front.colav.co /home/ci-front/Chia/guatquyca/run-devops.sh next_develop

  deploy_from_merge:
    name: Deploy after PR merge to main
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker image for main
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          echo "Deploying main branch"
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ci-front@ci-front.colav.co /home/ci-front/Chia/guatquyca/run-devops.sh main
